### ISSUE TITLE
While upload is running, core pings dropped (use multiple files)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/telemetry-ios#20]
The upload process runs in the background, however if the app continues to send events to it, those events will get dropped.
The upload grabs an immutable copy of the data, and then when complete it writes out the CorePing json as either empty or with remaining pings that didn't send.
If the app is brought to foreground during the upload, which means telemetry events will happen, that data will be dropped while the upload task is still running.

Solution:
Once a JSON file is being uploaded, it could be renamed (just appending a timestamp to the name should be fine), then new data could be written to a coreping JSON.
When uploading
1) move the coreping.json to coreping-timestamp.json
2) iterate all the core ping files to read the data immutably in memory
3) write out un-uploaded pings to their coreping-timestamp.json files

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla-mobile/telemetry-ios/pull/31

**Comment by justindarc** [comment]
Umm.. I had this issue assigned to myself and I've been working on this in a local branch that's almost ready. I thought it was clear that I was already doing this work. We need to do a better job coordinating so we're not duplicating work.

**Comment by garvankeeley** [comment]
Sorry, I don't recall you mentioning it, and I also was working on it and didn't look at the patch assignment. We'll have to coordinate better 👍 .

**Comment by justindarc** [comment]
Its ok. I thought I had mentioned it in Slack, but oh well... I left a comment on your PR discussing the differences between your patch and my WIP branch. Because our approaches differ in how they store the pings, I don't think this is something we can easily iterate on and we need to decide which one we want to push forward. I'm strongly in favor of one ping per file since it gives us filesystem-level flexibility to deal with queuing/dequeuing individual pings and we wouldn't have to deal with renaming.

**Comment by garvankeeley** [comment]
Your new method sgtm. This issue is the only known one left that could affect uploads on `dev` branch (I hope!), so that patch is just to complete the work on the current method. My intention on the patch was just to 'nest the loop' so-to-speak to take the once per file closure and loop over multiple  files. I am not going further code-wise with this and I am not attached to the many-dict-per-file current method.
I think this bug is specific to the current implementation and isn't likely to be an issue in your new method.

**Comment by garvankeeley** [comment]
My requests on this issue are:
1) File a separate bug for your storage refactor, I filed this bug as a reminder to complete the repair work on the existing design. I think the current bug description is accurate as to the current implementation bug so I would rather not re-purpose this bug.

2) Decide whether we want to land my patch to bring the old code to a certain level of completion (this being the last known uploader bug).
This isn't a big change, and should be mergeable into your branch. Your refactor might overwrite this uploader loop entirely and merging is less of an issue in that case.

**Comment by garvankeeley** [comment]
Your patch looks good, I'll close mine and get yours reviewed later today after I finish looking at #39
