### ISSUE TITLE
Playground should be updated for new upload behaviour

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/telemetry-ios#24]
The playground needs a sample of async usage, the current loop-with-sleep won't run more than once with latest changes on `dev` branch; each upload needs the event loop to spin, then complete, then add another upload, etc.

**Comment by justindarc** [comment]
I don't believe this is still an issue with the new `TelemetryStorage` implementation with the `Sequence` approach we used. The `TelemetryScheduler` will iterate through all the pings and check for any additional pings queued when it reaches the end until there are no more pings left to upload.

**Comment by justindarc** [comment]
After fixing the issue with multiple background tasks, I can confirm that this does now indeed work. Closing.
