### ISSUE TITLE
Include support for Cocoapods

### ISSUE THREAD

**Issue by brendanlensink** [mozilla-mobile/telemetry-ios#29]
Are there currently any plans to support CocoaPods?

Doing so is fairly straightforward and would be helpful for future projects. Instructions on how to do so are available [here](https://guides.cocoapods.org/making/making-a-cocoapod.html).

**Comment by garvankeeley** [comment]
No plans but we would be happy for contribs on that.
We are using it with Carthage in Firefox iOS, as a no-binary dependency.
