### ISSUE TITLE
Telemetry client should not send cookies

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/telemetry-ios#32]
I see the following being added to requests:

`Cookie: optimizelyBuckets=%7B%7D; optimizelySegments=%7B%22245984388%22%3A%22true%22%2C%22246002457%22%3A%22campaign%22%2C%22246073289%22%3A%22none%22%2C%22246073290%22%3A%22safari%22%7D; optimizelyEndUserId=oeu1506111227235r0.2246110569576656`

This cookie is picked up when visiting `mozilla.org`. Technically this is correct, but we should not do this. The Telemetry client should work in a sandboxed mode, not picking up any data from other clients like the WKWebView or our other clients.

**Comment by garvankeeley** [comment]
👍 I think there is a config option on URLSession to ignore the cookies.

**Comment by garvankeeley** [comment]
Fixed by 15b654e, setting URLRequest.httpShouldHandleCookies = false
