### ISSUE TITLE
Remove debug logging / safeguard print() to debug only

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/telemetry-ios#54]
I think the library has a debug `println` somewhere because I see lines like this in my console:

> Request Body: {"tz":-240,"sessions":3,"durations":20,"clientId":"A862CBDE-4C06-4BF1-98D4-131032B743E5","profileDate":17449,"v":7,"device":"x86_64","defaultSearch":"unknown","locale":"sv-SE","seq":1,"os":"iOS","osversion":"11.0.1","created":"2017-10-17","arch":"x86_64"}

**Comment by garvankeeley** [comment]
It does, and I make use of those, you should see ~1 per session when app backgrounded.
