### ISSUE TITLE
Don't log on the simulator

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/telemetry-ios#55]
Maybe it is a good idea to do a check for the simulator in the library and don't log anything? With a good number of developers, contributors and CI systems, we may be able to generate a decent amount of noise?

**Comment by garvankeeley** [comment]
You mean Sentry logging? Otherwise I am confused about log noise, it should be minimal. That said, any print statements are temporary, I can remove them and just add them when needed locally.

**Comment by garvankeeley** [comment]
fixed by ef2edab
