### ISSUE TITLE
Implement MobileEventPing

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/telemetry-ios#78]
We need to implement the `mobile-event` ping in this client library to coincide with the ongoing work to get it implemented on the server side. This ping format is effectively identical to `focus-event` in every way except by name.

**Comment by justindarc** [comment]
Will also need to update to add `device` and `arch` fields to both the `mobile-event` and `focus-event` pings.

See: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/101

**Comment by pocmo** [comment]
What is the mobile-event ping and should Focus for Android use this too? Or is this for Firefox?

**Comment by justindarc** [comment]
It is basically identical to `focus-event`, in every way but by name. The reason is to make it easier for us to add in UI event telemetry to additional mobile apps in the future and not just Focus. I believe the intention is to eventually migrate Focus away from using `focus-event` to `mobile-event` instead, but that will happen a bit later.

**Comment by pocmo** [comment]
Thanks. This means Rocket should use mobile-event (They are using focus-event currently).
